# General properties of model runs {#sec-general-props}

## Consistency of theory and commitments

**Background**

A weak requirement of an RE state (and a consequence of full and exclusive account required for full RE) is that commitments and theory of a fixed point or a global optimum have to be consistent with each other, i.e. the union of commitments and theory has to be dialectically consistent.

**Method**

We store the consistency status of the union of commitments and theory for every fixed point and global optima resulting from a configuration during the creation of an ensemble.

**Results**
*Observations:*
- In ensemble 07 the relative share of consistent unions among both global optima and fixed points is roughly 75%. For the other ensembles, linear models perform slightly bettter than quadratic variants for global optima: 56% (QDS), 66% (QPS)  vs. 79% (LDS, LPS) in ensemble 08,  and 46% (QDS), 57% (QPS)  vs. 61% (LDS),  64% (LPS) in ensemble 09.
- there is no salient difference in the relative share of consistent unions for fixed points and global optima
- the difference of relative shares of consistent commitments exceeds the one of consistent unions by roughly 5% (percentage points).

**Conclusion**

The observed excess indicates, that in roughly 5% of cases for all model variants, the commitments of fixed points or global optima are consistent by themselves, but inconsistent with the theory. It may be interesting to explore, whether there are other aspects of configurations (e.g. low weight for account) that provoke such cases.


## Process Lenght

<!-- 
Relevant documents:

+ <https://github.com/debatelab/re-studies/blob/master/projects/ensemble_study_02/ensemble-study-02-dataexploration-template.ipynb>
+ <https://github.com/debatelab/re-studies/blob/master/projects/ensemble_study_02/ensemble-study-02-dataexploration-07.ipynb>

Remarks/Todos:

+ What do we want to add here from <https://github.com/debatelab/re-studies/blob/master/projects/ensemble_study_02/ensemble-study-02-dataexploration-07.ipynb>
-->

**Background**

The length of an RE process is defined as the number of adjustment steps that bring about a change in the commitments or the theory. In contrast to the implemented stopping rule (check after even-numbered steps, and inclusion of steps without change), this definition is closer to a intuitive understanding of how long an RE process is.

**Method**

<!-- ToDo
+ Revise: Implementation details are not relevant. (I guess, we could also do without a "method" section.) 
-->
<!--
The length of an RE process is stored for the fixed point of the main branch. The lengths of processes in other branches are ignored, since this feature has not been selected as a consolidation criterion. There is a section in the (template)[https://git.scc.kit.edu/debatelab/re-python/-/blob/master/projects/ensemble_study_02/ensemble-study-02-dataexploration-template.ipynb] for dataexploration concerning the length of RE processes.
-->

**Results**


A noteworthy finding in all ensembles is the short length of RE processes, which is even more accentuated for linear models. <!--There is a more detailed (exploration)[https://git.scc.kit.edu/debatelab/re-python/-/blob/master/projects/ensemble_study_02/ensemble-study-02-dataexploration-07.ipynb] of process lengths in ensemble 06 (including the size of jumps in individual steps), where 78.9% of processes have lenght 2, and 99.6% have length $\leq 3$. -->
In ensemble 06 (including the size of jumps in individual steps), 78.9% of processes have lenght 2, and 99.6% have length $\leq 3$.

**Conclusion**

In view of the semi-global approach to adjustment steps (i.e. the consideration of all candidates for theories or commitments in contrast to genuine piece-meal adjustment of single elements) short processes are expectable and do not speak in favour or against a model variant.

## Principles

<!-- 
Relevant documents:

+ <https://github.com/debatelab/re-studies/blob/master/projects/ensemble_study_02/ensemble-study-02-dataexploration-06.ipynb>

Remarks/Todos:

+ What do we want to add here from <https://github.com/debatelab/re-studies/blob/master/projects/ensemble_study_02/ensemble-study-02-dataexploration-06.ipynb>
-->

**Background**

The new generation of random arguments allows to ensure that the dialectical structures includes principles, i.e. sentences that only occur as premises in arguments. Consequently, principles have potential to account for other sentences (maybe together wit auxiliary premises).  The question is whether fixed points or global optima tend to include principles in their theories.


**Method**

*Definition*: A sentence is a principle of multiplicity $n$ in a dialectical structure iff (i) it occurs in exactly $n$ arguments as a premise and (ii) it or its negation does not occur as a conclusion in any argument. 

We generated ensemble 06 with at least two principles per dialectical structure (150 structures). Upon initialization, the principles and their multiplicity are saved as a list of tuples of the form (principle, multiplicity) in the dataframe. <!--The exploration of ensemble 06 with respect to principles can be found in [dataexploration 06](https://git.scc.kit.edu/debatelab/re-python/-/blob/master/projects/ensemble_study_02/ensemble-study-02-dataexploration-06.ipynb).--> The study only included principles with multiplicity $`\geq`$ 2 and addressed the following questions:
- Comparison with a chance model for the expected number of principles occurring in if theories were selected randomly.
- Are principles in initial commitments preserved/transferred to fixed point theories?


**Results**

*Observations*
- the number of principles with multiplicity $\geq 2$ is normally distributed around 2.

*Chance model*
- in most cases the mean number of principles in fixed point theories is higher than the expected number by chance

*Preservation of principles*
- in most of processes the amount of principles does not change from initial commitments to fixed point theory.
- QDS performs better with respect to the mean difference of principles in initial commitments and theory (QDS: 0.0) than the other variants (QPS, LDS, LPS: -0.18)
- the difference of principles in intial commitments and theory depends on the number of principles in the initial commitments. Only for initial commitments without principles the difference is positive. Again, QDS performs best.

**Conclusion**

The results are interesting but not decisive or well understood for the consolidation of the model.There are many open questions concerning the current implementation of principles:

- Is the definition of principles reasonble in view of alternatives?
- Is it possible to define other important and related concepts syntactically (e.g. additional or background assumptions, evidence etc.)?
- Is the chance model too benevolent?
- Should we consider only those principles, which are not elements of the initial commitments?
- Should the chance model consider the distribution of principles in the set of all consistent and complete positions?

In contrast to later ensembles, ensemble 06 does not completely track all fixed points and global optima for a configuration. It may be interesting to explore principles in a newly generated ensemble, which allows to study all fixed points as well as global optima.


## Replication of published Results

<!--
+ ToDo: move to footnote/appendix and the corresponding notebook.
-->

<!-- Relevant documents/links:
+ <https://github.com/debatelab/re-studies/blob/master/notebooks/replication_of_paper_results.ipynb>
-->

**Background**

The published paper includes a study based on a Mathematica implementation of Gregor Betz ((GitHub reposistory)[https://github.com/debatelab/remoma]).

**Method**
The studies of the pupblished paper include two ensembles. 

**Results**

The Python implementation of the published model (QuadraticDefaultSystematicityRE) is able to replicate the results from the Mathematica implementation from the published paper<!--, as can be seen [here](https://git.scc.kit.edu/debatelab/re-python/-/blob/master/notebooks/replication_of_paper_results.ipynb)-->.

**Conclusion**