# Commitment consistency cases {#sec-commitment-consistency}

**Background**

Consistency is commonly seen as a necessary condition of coherence, thus, if RE is taken to involve coherentist aspects, achieveing consistency is of utmost importance. This study considers the *dialectical consistency* (opposed to minimal consistency, i.e. the absence of flat contradictions, and the dialectical consistency of commitments plus a theory) of initial and endpoint commitments. The endpoint commitments stem either from a global optima or from a fixed point. The juxtaposition of initial and endpoint commitments allows for four cases, which are labelled as follows:

|                                   | endpoint commitments consistent   | endpoint commitment inconsistent  |
| ------                            | ------                            | ----                              |
| initial commitments consistent    | good                              | very bad                          |
| initial commitments inconsistent  | very good                         | bad                               |

Good case preserve or "transfer" consistency between intial and enpoint commitments. In very good cases, inconsistent initial commitments are revised for consistent endpoint commitments. Bad cases fail to eradicate initial inconsistencies and it is very bad if inconsistencies are introduced to initially consistent commitments.

**Method**

During the generation of an ensemble we store the consistency status of intial commitments as well as the status for every commitment from global optima or fixed points for every configuration, and label them accordingly. Again, the number of global optima (fixed points) for a case type is put into relation with the total number of global optima (fixed points) for every configuration.

Good cases are not included in the consolidation. Surely, good cases are a desirable feature of RE, but the other cases seem to be more relevant/interesting for consolidating the models, because the strengths or weaknesses of RE are often discussed for such cases. Since commitment consistency cases are exhaustive, good cases take up the rest.

**Results**

*Observations: Very good cases*

- The relative share of very good cases among global optima and fixed points varies between 10.3% (QDS, ensemble 08) and 22.7% (LDS, ensemble 07)
- Linear models have higher relative shares than quadratic variants in ensembles 08 and 09. 
- The relative share of very good cases among global optima does not exceed its counterpart for fixed points (In ensemble 09, the converse holds.)

- linear model have a "tipping line" for very good cases among both global optima and fixed points
- very good cases occur only below the "tippling line" in linear models
- the mean relative share (and the standard deviation) below the tipping line in linear model are completely uniform.
- all model variants have regions in there heatmpas, where no very good cases occur at all, the maximal relative share of is 37% (ensebmle 07 and 08)/ 47% (ensemble 09) for both global and fixed points

- quadraatic models have smooth transitions
- in quadratic models, high weights for account and low weight for faithfulness benefit the relative share of very good cases among global optima and fixed points

*Observations: Bad cases*

- The relative share of bad cases among global optima varies between 14.8% (LDS, ensemble 08) and 33.8% (QDS, ensemble 09)
- quadratic models have a higher share of bad cases than linear variants in ensembles 08 and 09. 
- The relative share of bad cases among global optima tend to exceed its counterpart for fixed points (In ensemble 09, the converse holds for linear models.)

- linear model have a "tipping line" for bad cases among both global optima and fixed points
- bad cases occur only above the "tippling line" in linear models
- the mean relative share (and the standard deviation) above the tipping line in linear model are completely uniform.
- all model variants have regions in there heatmpas, where no bad cases occur at all, the maximal relative share of is 37% (ensebmle 07 and 08)/ 47% (ensemble 09) for both global and fixed points

- quadraatic models have smooth transitions
- in quadratic models, high weights for faithfulness and low weight for account increase the relative share of bad cases among global optima and fixed points.

*Observations: Very bad cases*

- The relative share of very bad cases among global optima varies between 1.3% (LDS, ensemble 07) and 13.0% (QDS, ensemble 09)
- The relative share of very bad cases among fixed points varies between 0.4% (LPS, ensemble 07) and 8.7% (QDS, ensemble 08)
- quadratic models have a higher share of very bad cases than linear variants for both global optima and fixed points in all ensembles. 
- The relative share of very bad cases among global optima exceed its counterpart for fixed points

- linear model have a "tipping line" for very bad cases among both global optima and fixed points
- very bad cases occur only above the "tippling line" in linear models

- all model variants have regions in there heatmpas, where no very bad cases occur at all

- quadraatic models have smooth transitions
- in quadratic models, low weights for account increase the relative share of very bad cases among global optima and fixed points.


**Conclusion**

<!--
What do we want to add from <https://github.com/debatelab/re-studies/blob/master/projects/ensemble_study_02/ensemble-study-02-dataexploration-04.ipynb>?
-->



Overall, linear models tend to perform better than quadratic variants for all cases, but every model variant has combinations of weights where very (bad) cases disapear and very good cases occur more often. Even very bad cases cannot serve as an exclusion criteria. They have a (very) small share and their manifestation may depend on additional input features (e.g. the size of initial commitmen or their minimal axiomatizsation). <!--A description how an RE process creates a very bad case can be found in [dataexploration-04](https://github.com/debatelab/re-studies/blob/master/projects/ensemble_study_02/ensemble-study-02-dataexploration-04.ipynb) of an earlier ensemble.-->