# Preface {.unnumbered}

<!--
ToDos:
+ Add howto cite info.
+ Add abstract.
+ Add a graphical representation of the report's structure.
+ Make links to package docs perhaps more visible (how?) 
-->

This report summarizes findings of analysing a formal model of the method of reflective equilibrium. The model is based on @beisbart_making_2021.


## Reproducibility

All findings and the underlying data can be reproduced by using the [Python implementation]({{< var link.rethon >}}) of the model. The data that the model produced can be found [here]({{< var link.reproduction-data >}}). For each chapter you will find [here]({{< var link.reproduction-notebooks >}}) a Jupyter notebook whose execution produces all analysis results. 

## Licence

This report is licenced under ...

## Credits

Earlier versions of this report were discussed on several occasions with all members of the research project  ['How far does Reflective Equilibrium Take us? Investigating the Power of a Philosophical Method'](https://www.philosophie.unibe.ch/forschung/forschungsprojekte/how_far_does_reflective_equilibrium_take_us/project/index_ger.html) (SNSF grant 182854 and German Research Foundation grant 412679086). We thank, in particular, Claus Beisbart, Gregor Betz, Georg Brun, Alexander Koch and Richard Lohse for their helpful comments, which helped to improve this report considerably.